image:
  repository: gcr.io/project-df2823f4-a3b3-4db0-a90/nexus3-gcs
  tag: "3.57.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8081
  targetPort: 8081

persistence:
  enabled: true
  storageClass: "standard-rwo"
  size: 10Gi
  accessMode: ReadWriteOnce

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: "2"
    memory: 4Gi

serviceAccount:
  create: true
  name: nexus-sa
  annotations:
    iam.gke.io/gcp-service-account: "nexus-sa@project-df2823f4-a3b3-4db0-a90.iam.gserviceaccount.com"

gcs:
  bucketName: "nexus-on-gke-bucket-192837648"

env:
  - name: INSTALL4J_ADD_VM_PARAMS
    value: "-Xms1g -Xmx2g -XX:ActiveProcessorCount=2"
